In [1]:
import pandas as pd

In [2]:
dataset=pd.read_csv("insurance_pre.csv")

In [3]:
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [4]:
dataset=pd.get_dummies(dataset,dtype=int,drop_first=True)

In [5]:
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [6]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [7]:
independent=dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]
independent

      age     bmi  children  sex_male  smoker_yes
0      19  27.900         0         0           1
1      18  33.770         1         1           0
2      28  33.000         3         1           0
3      33  22.705         0         1           0
4      32  28.880         0         1           0
...   ...     ...       ...       ...         ...
1333   50  30.970         3         1           0
1334   18  31.920         0         0           0
1335   18  36.850         0         0           0
1336   21  25.800         0         0           0
1337   61  29.070         0         0           1

[1338 rows x 5 columns]

In [8]:
dependent=dataset[['charges']]
dependent

          charges
0     16884.92400
1      1725.55230
2      4449.46200
3     21984.47061
4      3866.85520
...           ...
1333  10600.54830
1334   2205.98080
1335   1629.83350
1336   2007.94500
1337  29141.36030

[1338 rows x 1 columns]

In [9]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(independent,dependent,test_size=0.30,random_state=0)

In [10]:
from sklearn.model_selection import GridSearchCV

In [18]:
from sklearn.model_selection import GridSearchCV
from sklearn.tree import DecisionTreeRegressor
param_grid = {'criterion':['squared_error','absolute_error','friedman_mse'],
              'max_features': [None, 'sqrt', 'log2'],
              'splitter':['best','random']}
grid = GridSearchCV(DecisionTreeRegressor(), param_grid, refit = True, verbose= 3,n_jobs=-1)
grid.fit(independent,dependent)

Fitting 5 folds for each of 18 candidates, totalling 90 fits

GridSearchCV(estimator=DecisionTreeRegressor(), n_jobs=-1,
             param_grid={'criterion': ['squared_error', 'absolute_error',
                                       'friedman_mse'],
                         'max_features': [None, 'sqrt', 'log2'],
                         'splitter': ['best', 'random']},
             verbose=3)

In [19]:
re=grid.cv_results_
grid_predictions=grid.predict(x_test)
from sklearn.metrics import r2_score
r_score=r2_score(y_test,grid_predictions)
print("The R_score value for best parameter {}:".format(grid.best_params_))

The R_score value for best parameter {'criterion': 'friedman_mse', 'max_features': 'log2', 'splitter': 'best'}:

In [20]:
table=pd.DataFrame.from_dict(re)

In [21]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_criterion,param_max_features,param_splitter,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.036482,0.003823,0.009852,1.336480e-03,squared_error,None,best,"{'criterion': 'squared_error', 'max_features':...",0.717235,0.656409,0.725626,0.743604,0.662089,0.700992,0.035178,4
1,0.022085,0.003054,0.010249,2.641477e-03,squared_error,None,random,"{'criterion': 'squared_error', 'max_features':...",0.708531,0.646205,0.739782,0.713296,0.711321,0.703827,0.030922,3
2,0.023422,0.000816,0.009977,8.891502e-04,squared_error,sqrt,best,"{'criterion': 'squared_error', 'max_features':...",0.559566,0.603073,0.752916,0.699340,0.735849,0.670149,0.075824,13
3,0.017754,0.001163,0.008377,4.884998e-04,squared_error,sqrt,random,"{'criterion': 'squared_error', 'max_features':...",0.759026,0.382965,0.661071,0.521336,0.655757,0.596031,0.130646,18
4,0.024933,0.005606,0.009974,2.442518e-03,squared_error,log2,best,"{'criterion': 'squared_error', 'max_features':...",0.690914,0.523206,0.678955,0.547986,0.712709,0.630754,0.078837,16
5,0.016757,0.000746,0.007976,7.168434e-07,squared_error,log2,random,"{'criterion': 'squared_error', 'max_features':...",0.720314,0.616113,0.647368,0.685101,0.422237,0.618227,0.104077,17
6,0.108510,0.002801,0.007735,1.378813e-03,absolute_error,None,best,"{'criterion': 'absolute_error', 'max_features'...",0.727151,0.607810,0.709529,0.715898,0.737040,0.699486,0.046798,5
7,0.079710,0.007033,0.008452,1.298139e-03,absolute_error,None,random,"{'criterion': 'absolute_error', 'max_features'...",0.712255,0.640697,0.683279,0.727920,0.720657,0.696961,0.031958,6
8,0.073839,0.011220,0.007932,6.479663e-04,absolute_error,sqrt,best,"{'criterion': 'absolute_error', 'max_features'...",0.721160,0.599045,0.657536,0.645778,0.731229,0.670949,0.049272,12
9,0.057162,0.010470,0.007992,6.508958e-04,absolute_error,sqrt,random,"{'criterion': 'absolute_error', 'max_features'...",0.709549,0.584803,0.687242,0.683282,0.702350,0.673445,0.045351,11
10,0.068421,0.006081,0.007380,1.620634e-03,absolute_error,log2,best,"{'criterion': 'absolute_error', 'max_features'...",0.739116,0.598394,0.605524,0.728714,0.710031,0.676356,0.061497,9
11,0.044480,0.006480,0.007837,1.070530e-03,absolute_error,log2,random,"{'criterion': 'absolute_error', 'max_features'...",0.692798,0.524543,0.709660,0.730410,0.710493,0.673581,0.075465,10
12,0.032529,0.004481,0.008410,4.648487e-04,friedman_mse,None,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.723915,0.646460,0.729664,0.708536,0.662814,0.694278,0.033497,7
13,0.020348,0.000805,0.007776,9.761322e-04,friedman_mse,None,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.691883,0.583063,0.709151,0.702589,0.751598,0.687657,0.056091,8
14,0.022145,0.001592,0.007376,4.903196e-04,friedman_mse,sqrt,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.751137,0.632395,0.697020,0.758957,0.729465,0.713795,0.046015,2
15,0.017401,0.003234,0.008281,1.238827e-03,friedman_mse,sqrt,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.651331,0.560085,0.688167,0.706696,0.699356,0.661127,0.053990,14
16,0.022546,0.000536,0.007809,7.200543e-04,friedman_mse,log2,best,"{'criterion': 'friedman_mse', 'max_features': ...",0.762854,0.634901,0.773532,0.748375,0.714516,0.726835,0.050091,1
17,0.014588,0.001029,0.006982,6.305250e-04,friedman_mse,log2,random,"{'criterion': 'friedman_mse', 'max_features': ...",0.580626,0.578811,0.694316,0.609086,0.698459,0.632260,0.053466,15

In [22]:
age_input=float(input("Age:"))
bmi_input=float(input("BMI:"))
children_input=float(input("Children:"))
sex_male_input=int(input("Sex Male 0 or 1:"))
smoker_yes_input=int(input("Smoker Yes 0 or 1:"))

Age:32
BMI:43
Children:2
Sex Male 0 or 1:1
Smoker Yes 0 or 1:1

In [23]:
Future_Prediction=grid.predict([[age_input,bmi_input,children_input,sex_male_input,smoker_yes_input]])
print("Future_Prediction={}".format(Future_Prediction))

Future_Prediction=[43753.33705]

C:\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but DecisionTreeRegressor was fitted with feature names
  warnings.warn(

In [24]:
print("The Best r_score: ",r_score)

The Best r_score:  0.9985711630437506