In [1]:
import pandas as pd

In [2]:
dataset=pd.read_csv("insurance_pre.csv")

In [3]:
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [4]:
dataset=pd.get_dummies(dataset,dtype=int,drop_first=True)

In [5]:
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [6]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [7]:
independent=dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]
independent

      age     bmi  children  sex_male  smoker_yes
0      19  27.900         0         0           1
1      18  33.770         1         1           0
2      28  33.000         3         1           0
3      33  22.705         0         1           0
4      32  28.880         0         1           0
...   ...     ...       ...       ...         ...
1333   50  30.970         3         1           0
1334   18  31.920         0         0           0
1335   18  36.850         0         0           0
1336   21  25.800         0         0           0
1337   61  29.070         0         0           1

[1338 rows x 5 columns]

In [8]:
dependent=dataset[['charges']]
dependent

          charges
0     16884.92400
1      1725.55230
2      4449.46200
3     21984.47061
4      3866.85520
...           ...
1333  10600.54830
1334   2205.98080
1335   1629.83350
1336   2007.94500
1337  29141.36030

[1338 rows x 1 columns]

In [9]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(independent,dependent,test_size=0.30,random_state=0)

In [10]:
from sklearn.model_selection import GridSearchCV

In [11]:
from sklearn.linear_model import LinearRegression
param_grid= { "fit_intercept": [True, False],'copy_X':[True,False],'n_jobs':[1,-1,None],
             'positive':[True,False]}
grid = GridSearchCV(LinearRegression(), param_grid,refit=True,verbose=3, n_jobs=-1)
grid.fit(x_train, y_train)

Fitting 5 folds for each of 24 candidates, totalling 120 fits

GridSearchCV(estimator=LinearRegression(), n_jobs=-1,
             param_grid={'copy_X': [True, False],
                         'fit_intercept': [True, False],
                         'n_jobs': [1, -1, None], 'positive': [True, False]},
             verbose=3)

In [12]:
re=grid.cv_results_
grid_predictions=grid.predict(x_test)
from sklearn.metrics import r2_score
r_score=r2_score(y_test,grid_predictions)
print("The R_score value for best parameter {}:".format(grid.best_params_))

The R_score value for best parameter {'copy_X': True, 'fit_intercept': True, 'n_jobs': 1, 'positive': True}:

In [13]:
table=pd.DataFrame.from_dict(re)

In [14]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_copy_X,param_fit_intercept,param_n_jobs,param_positive,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.016927,0.005057,0.008124,0.002967,True,True,1,True,"{'copy_X': True, 'fit_intercept': True, 'n_job...",0.763511,0.703146,0.730655,0.695634,0.719080,0.722405,0.023902,1
1,0.048590,0.025392,0.006738,0.000865,True,True,1,False,"{'copy_X': True, 'fit_intercept': True, 'n_job...",0.763511,0.702938,0.730655,0.695551,0.719087,0.722348,0.023954,7
2,0.024258,0.004451,0.007632,0.000832,True,True,-1,True,"{'copy_X': True, 'fit_intercept': True, 'n_job...",0.763511,0.703146,0.730655,0.695634,0.719080,0.722405,0.023902,1
3,0.010226,0.002899,0.009309,0.005464,True,True,-1,False,"{'copy_X': True, 'fit_intercept': True, 'n_job...",0.763511,0.702938,0.730655,0.695551,0.719087,0.722348,0.023954,7
4,0.012728,0.003018,0.008346,0.002428,True,True,None,True,"{'copy_X': True, 'fit_intercept': True, 'n_job...",0.763511,0.703146,0.730655,0.695634,0.719080,0.722405,0.023902,1
5,0.011146,0.002313,0.012987,0.007543,True,True,None,False,"{'copy_X': True, 'fit_intercept': True, 'n_job...",0.763511,0.702938,0.730655,0.695551,0.719087,0.722348,0.023954,7
6,0.015719,0.011360,0.007594,0.001101,True,False,1,True,"{'copy_X': True, 'fit_intercept': False, 'n_jo...",0.743115,0.657160,0.699508,0.657341,0.684679,0.688361,0.031848,19
7,0.016367,0.009389,0.006531,0.000706,True,False,1,False,"{'copy_X': True, 'fit_intercept': False, 'n_jo...",0.744435,0.657009,0.700806,0.657076,0.686170,0.689099,0.032444,13
8,0.043124,0.013928,0.008331,0.000907,True,False,-1,True,"{'copy_X': True, 'fit_intercept': False, 'n_jo...",0.743115,0.657160,0.699508,0.657341,0.684679,0.688361,0.031848,19
9,0.009762,0.001263,0.006870,0.001071,True,False,-1,False,"{'copy_X': True, 'fit_intercept': False, 'n_jo...",0.744435,0.657009,0.700806,0.657076,0.686170,0.689099,0.032444,13
10,0.012427,0.002583,0.008669,0.001818,True,False,None,True,"{'copy_X': True, 'fit_intercept': False, 'n_jo...",0.743115,0.657160,0.699508,0.657341,0.684679,0.688361,0.031848,19
11,0.010111,0.001976,0.008151,0.000861,True,False,None,False,"{'copy_X': True, 'fit_intercept': False, 'n_jo...",0.744435,0.657009,0.700806,0.657076,0.686170,0.689099,0.032444,13
12,0.011722,0.002023,0.007132,0.001246,False,True,1,True,"{'copy_X': False, 'fit_intercept': True, 'n_jo...",0.763511,0.703146,0.730655,0.695634,0.719080,0.722405,0.023902,1
13,0.013629,0.003509,0.008833,0.002384,False,True,1,False,"{'copy_X': False, 'fit_intercept': True, 'n_jo...",0.763511,0.702938,0.730655,0.695551,0.719087,0.722348,0.023954,7
14,0.033860,0.008022,0.007083,0.000757,False,True,-1,True,"{'copy_X': False, 'fit_intercept': True, 'n_jo...",0.763511,0.703146,0.730655,0.695634,0.719080,0.722405,0.023902,1
15,0.008044,0.000559,0.006839,0.000807,False,True,-1,False,"{'copy_X': False, 'fit_intercept': True, 'n_jo...",0.763511,0.702938,0.730655,0.695551,0.719087,0.722348,0.023954,7
16,0.011777,0.005452,0.008744,0.003818,False,True,None,True,"{'copy_X': False, 'fit_intercept': True, 'n_jo...",0.763511,0.703146,0.730655,0.695634,0.719080,0.722405,0.023902,1
17,0.009512,0.000441,0.006296,0.000750,False,True,None,False,"{'copy_X': False, 'fit_intercept': True, 'n_jo...",0.763511,0.702938,0.730655,0.695551,0.719087,0.722348,0.023954,7
18,0.010820,0.003237,0.007499,0.001065,False,False,1,True,"{'copy_X': False, 'fit_intercept': False, 'n_j...",0.743115,0.657160,0.699508,0.657341,0.684679,0.688361,0.031848,19
19,0.008995,0.000653,0.007724,0.001313,False,False,1,False,"{'copy_X': False, 'fit_intercept': False, 'n_j...",0.744435,0.657009,0.700806,0.657076,0.686170,0.689099,0.032444,13
20,0.036486,0.014867,0.006799,0.000549,False,False,-1,True,"{'copy_X': False, 'fit_intercept': False, 'n_j...",0.743115,0.657160,0.699508,0.657341,0.684679,0.688361,0.031848,19
21,0.015553,0.008553,0.006118,0.000242,False,False,-1,False,"{'copy_X': False, 'fit_intercept': False, 'n_j...",0.744435,0.657009,0.700806,0.657076,0.686170,0.689099,0.032444,13
22,0.010181,0.000349,0.007394,0.001947,False,False,None,True,"{'copy_X': False, 'fit_intercept': False, 'n_j...",0.743115,0.657160,0.699508,0.657341,0.684679,0.688361,0.031848,19
23,0.010741,0.003295,0.006058,0.000606,False,False,None,False,"{'copy_X': False, 'fit_intercept': False, 'n_j...",0.744435,0.657009,0.700806,0.657076,0.686170,0.689099,0.032444,13

In [15]:
age_input=float(input("Age:"))
bmi_input=float(input("BMI:"))
children_input=float(input("Children:"))
sex_male_input=int(input("Sex Male 0 or 1:"))
smoker_yes_input=int(input("Smoker Yes 0 or 1:"))

Age:32
BMI:43
Children:2
Sex Male 0 or 1:1
Smoker Yes 0 or 1:1

In [16]:
Future_Prediction=grid.predict([[age_input,bmi_input,children_input,sex_male_input,smoker_yes_input]])
print("Future_Prediction={}".format(Future_Prediction))

Future_Prediction=[[34331.14424442]]

C:\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

In [17]:
print("The Best r_score: ",r_score)

The Best r_score:  0.7894429387120753