In [1]:
import pandas as pd

In [2]:
dataset=pd.read_csv("insurance_pre.csv")

In [3]:
dataset

      age     sex     bmi  children smoker      charges
0      19  female  27.900         0    yes  16884.92400
1      18    male  33.770         1     no   1725.55230
2      28    male  33.000         3     no   4449.46200
3      33    male  22.705         0     no  21984.47061
4      32    male  28.880         0     no   3866.85520
...   ...     ...     ...       ...    ...          ...
1333   50    male  30.970         3     no  10600.54830
1334   18  female  31.920         0     no   2205.98080
1335   18  female  36.850         0     no   1629.83350
1336   21  female  25.800         0     no   2007.94500
1337   61  female  29.070         0    yes  29141.36030

[1338 rows x 6 columns]

In [4]:
dataset=pd.get_dummies(dataset,dtype=int,drop_first=True)

In [5]:
dataset

      age     bmi  children      charges  sex_male  smoker_yes
0      19  27.900         0  16884.92400         0           1
1      18  33.770         1   1725.55230         1           0
2      28  33.000         3   4449.46200         1           0
3      33  22.705         0  21984.47061         1           0
4      32  28.880         0   3866.85520         1           0
...   ...     ...       ...          ...       ...         ...
1333   50  30.970         3  10600.54830         1           0
1334   18  31.920         0   2205.98080         0           0
1335   18  36.850         0   1629.83350         0           0
1336   21  25.800         0   2007.94500         0           0
1337   61  29.070         0  29141.36030         0           1

[1338 rows x 6 columns]

In [6]:
dataset.columns

Index(['age', 'bmi', 'children', 'charges', 'sex_male', 'smoker_yes'], dtype='object')

In [7]:
independent=dataset[['age', 'bmi', 'children','sex_male', 'smoker_yes']]
independent

      age     bmi  children  sex_male  smoker_yes
0      19  27.900         0         0           1
1      18  33.770         1         1           0
2      28  33.000         3         1           0
3      33  22.705         0         1           0
4      32  28.880         0         1           0
...   ...     ...       ...       ...         ...
1333   50  30.970         3         1           0
1334   18  31.920         0         0           0
1335   18  36.850         0         0           0
1336   21  25.800         0         0           0
1337   61  29.070         0         0           1

[1338 rows x 5 columns]

In [8]:
dependent=dataset[['charges']]
dependent

          charges
0     16884.92400
1      1725.55230
2      4449.46200
3     21984.47061
4      3866.85520
...           ...
1333  10600.54830
1334   2205.98080
1335   1629.83350
1336   2007.94500
1337  29141.36030

[1338 rows x 1 columns]

In [9]:
from sklearn.model_selection import GridSearchCV

In [10]:
from sklearn.linear_model import LinearRegression
param_grid= { "fit_intercept": [True, False],
             'copy_X':[True,False],
             'n_jobs':[1,-1,None],
             'positive':[True,False]}
grid = GridSearchCV(LinearRegression(), param_grid,refit=True,verbose=3, n_jobs=-1)
grid.fit(independent,dependent)

Fitting 5 folds for each of 24 candidates, totalling 120 fits

GridSearchCV(estimator=LinearRegression(), n_jobs=-1,
             param_grid={'copy_X': [True, False],
                         'fit_intercept': [True, False],
                         'n_jobs': [1, -1, None], 'positive': [True, False]},
             verbose=3)

In [11]:
re=grid.cv_results_
print("The R_score value for best parameter {}:".format(grid.best_params_))

The R_score value for best parameter {'copy_X': True, 'fit_intercept': True, 'n_jobs': 1, 'positive': True}:

In [14]:
y_pred = grid.predict(independent)

from sklearn.metrics import r2_score
r_score = r2_score(dependent, y_pred)
r_score

0.749694530346479

In [15]:
table=pd.DataFrame.from_dict(re)

In [16]:
table

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_copy_X,param_fit_intercept,param_n_jobs,param_positive,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,0.010076,0.002454,0.005711,0.001210,True,True,1,True,"{'copy_X': True, 'fit_intercept': True, 'n_job...",0.761482,0.708782,0.775584,0.731353,0.756751,0.746790,0.023778,1
1,0.016772,0.007963,0.006184,0.001934,True,True,1,False,"{'copy_X': True, 'fit_intercept': True, 'n_job...",0.760979,0.708733,0.775584,0.731367,0.756545,0.746642,0.023713,7
2,0.019572,0.002861,0.007034,0.000797,True,True,-1,True,"{'copy_X': True, 'fit_intercept': True, 'n_job...",0.761482,0.708782,0.775584,0.731353,0.756751,0.746790,0.023778,1
3,0.013896,0.007333,0.006852,0.001228,True,True,-1,False,"{'copy_X': True, 'fit_intercept': True, 'n_job...",0.760979,0.708733,0.775584,0.731367,0.756545,0.746642,0.023713,7
4,0.010405,0.001584,0.007494,0.001280,True,True,None,True,"{'copy_X': True, 'fit_intercept': True, 'n_job...",0.761482,0.708782,0.775584,0.731353,0.756751,0.746790,0.023778,1
5,0.009772,0.001163,0.006583,0.001198,True,True,None,False,"{'copy_X': True, 'fit_intercept': True, 'n_job...",0.760979,0.708733,0.775584,0.731367,0.756545,0.746642,0.023713,7
6,0.011326,0.002328,0.008802,0.002356,True,False,1,True,"{'copy_X': True, 'fit_intercept': False, 'n_jo...",0.727280,0.691876,0.735943,0.699020,0.729543,0.716732,0.017754,19
7,0.010512,0.001293,0.006693,0.000653,True,False,1,False,"{'copy_X': True, 'fit_intercept': False, 'n_jo...",0.727683,0.691272,0.738275,0.700259,0.727085,0.716915,0.017948,13
8,0.020558,0.005584,0.006990,0.000522,True,False,-1,True,"{'copy_X': True, 'fit_intercept': False, 'n_jo...",0.727280,0.691876,0.735943,0.699020,0.729543,0.716732,0.017754,19
9,0.010279,0.002429,0.006994,0.000973,True,False,-1,False,"{'copy_X': True, 'fit_intercept': False, 'n_jo...",0.727683,0.691272,0.738275,0.700259,0.727085,0.716915,0.017948,13
10,0.013743,0.007001,0.007035,0.001568,True,False,None,True,"{'copy_X': True, 'fit_intercept': False, 'n_jo...",0.727280,0.691876,0.735943,0.699020,0.729543,0.716732,0.017754,19
11,0.010329,0.001310,0.007903,0.001414,True,False,None,False,"{'copy_X': True, 'fit_intercept': False, 'n_jo...",0.727683,0.691272,0.738275,0.700259,0.727085,0.716915,0.017948,13
12,0.009711,0.001428,0.008358,0.000367,False,True,1,True,"{'copy_X': False, 'fit_intercept': True, 'n_jo...",0.761482,0.708782,0.775584,0.731353,0.756751,0.746790,0.023778,1
13,0.009474,0.002627,0.008417,0.002455,False,True,1,False,"{'copy_X': False, 'fit_intercept': True, 'n_jo...",0.760979,0.708733,0.775584,0.731367,0.756545,0.746642,0.023713,7
14,0.018465,0.001888,0.006713,0.001031,False,True,-1,True,"{'copy_X': False, 'fit_intercept': True, 'n_jo...",0.761482,0.708782,0.775584,0.731353,0.756751,0.746790,0.023778,1
15,0.009098,0.001136,0.006480,0.001462,False,True,-1,False,"{'copy_X': False, 'fit_intercept': True, 'n_jo...",0.760979,0.708733,0.775584,0.731367,0.756545,0.746642,0.023713,7
16,0.009865,0.001116,0.007384,0.000624,False,True,None,True,"{'copy_X': False, 'fit_intercept': True, 'n_jo...",0.761482,0.708782,0.775584,0.731353,0.756751,0.746790,0.023778,1
17,0.009129,0.001669,0.006797,0.000540,False,True,None,False,"{'copy_X': False, 'fit_intercept': True, 'n_jo...",0.760979,0.708733,0.775584,0.731367,0.756545,0.746642,0.023713,7
18,0.009992,0.001093,0.006921,0.000764,False,False,1,True,"{'copy_X': False, 'fit_intercept': False, 'n_j...",0.727280,0.691876,0.735943,0.699020,0.729543,0.716732,0.017754,19
19,0.008551,0.001100,0.008266,0.002142,False,False,1,False,"{'copy_X': False, 'fit_intercept': False, 'n_j...",0.727683,0.691272,0.738275,0.700259,0.727085,0.716915,0.017948,13
20,0.018881,0.002456,0.007050,0.001159,False,False,-1,True,"{'copy_X': False, 'fit_intercept': False, 'n_j...",0.727280,0.691876,0.735943,0.699020,0.729543,0.716732,0.017754,19
21,0.008088,0.002044,0.006633,0.000828,False,False,-1,False,"{'copy_X': False, 'fit_intercept': False, 'n_j...",0.727683,0.691272,0.738275,0.700259,0.727085,0.716915,0.017948,13
22,0.008947,0.000685,0.006582,0.000489,False,False,None,True,"{'copy_X': False, 'fit_intercept': False, 'n_j...",0.727280,0.691876,0.735943,0.699020,0.729543,0.716732,0.017754,19
23,0.007539,0.001279,0.006668,0.000568,False,False,None,False,"{'copy_X': False, 'fit_intercept': False, 'n_j...",0.727683,0.691272,0.738275,0.700259,0.727085,0.716915,0.017948,13

In [17]:
age_input=float(input("Age:"))
bmi_input=float(input("BMI:"))
children_input=float(input("Children:"))
sex_male_input=int(input("Sex Male 0 or 1:"))
smoker_yes_input=int(input("Smoker Yes 0 or 1:"))

Age:32
BMI:43
Children:2
Sex Male 0 or 1:1
Smoker Yes 0 or 1:0

In [18]:
Future_Prediction=grid.predict([[age_input,bmi_input,children_input,sex_male_input,smoker_yes_input]])
print("Future_Prediction={}".format(Future_Prediction))

Future_Prediction=[[10935.02980736]]

C:\anaconda3\Lib\site-packages\sklearn\base.py:464: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(

In [20]:
print("The Best r_score: ",r_score)

The Best r_score:  0.749694530346479